---
- name: variable playbook test
  hosts: localhost

  tasks: 
  - name: Ensure httpd package is present
    ansible.builtin.package:
      name: httpd
      state: latest
    notify: restart_httpd

  handlers:
  - name: Restart_httpd
    ansible.builtin.service:
      name: httpd
      state: restarted

# Handlers only run or trigger at the end of the playbook
# also we want to use notify and handler to run task only when changes occurred

# tasks:
# - name: Ensure httpd package is present
#   ansible.builtin.package:
#     name: httpd
#     state: latest
#   notify: restart httpd
# - name: Standarized index.html file
#   ansible.builtin.copy:
#     content: "This is my index.html file for {{ ansible_host }}"
#     dest: /var/www/html/index.html
#   notify: restart httpd